modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="tavares_additions"
version="0.2.0"
displayName="Tavares' Additions"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Tavares"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tavares_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration