modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="tavares_additions"
version="0.2.0"
displayName="Tavares' Additions"
displayURL="https://github.com/NeverKnowBest/Tavares-Additions"
credits="Tavares"
authors="Tavares"
description="Adding things that i want"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tavares_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration